name: Cleanup Releases

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  schedule:
   - cron: 59 22 1,16 * *

env:
  TZ: Asia/Tokyo

permissions:
  actions: write
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-22.04

    steps:
    - name: 准备完成
      uses: actions/checkout@main

    - name: 删除运行记录
      uses: GitRML/delete-workflow-runs@main
      with:
        keep_minimum_runs: 3
        retain_days: 45

    - name: 删除自动发布的旧固件
      uses: dev-drprasad/delete-older-releases@v0.3.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        keep_latest: 4
        delete_tags: true
